function [mainSys, mainStates, mainParams, payloadSys, payloadStates, payloadParams] = solveComp(configParams)

if nargin < 1
configParams = struct(...
  'disableJettison', false, ...
  'noMotor', false, ...
  'motorLossFactor', 0.965, ...
  'noBallast', false, ...
  'launchAngle', 5, ...
  'launchSiteElevation', 800, ...
  'launchSiteTemp', 60, ...
  'launchSitePressurePa', 91550, ...
  'motorOverride', 'L1720', ...
  'launchRailEffectiveTravel', 12, ... % ft
  'windSpeed', 7, ...
  'driftCalcWindSpeed', 5);
end

mainSys = VADL.config.getMainSys(configParams);

solver = DRSS.solver.MatlabODESolver(mainSys) ...
  .setCaptureResultantParameters(true) ...
  .setPrintPerformanceSummary(true) .....
  .configureODE('RelTol', 1e-12, 'MaxStep', 0.05) ...
  .overrideODEFunc(@ode113);

[mainStates, mainParams] = solver.solve();

[payloadSys, payloadStates, ~] = VADL.sims.payload(mainSys, mainStates);

payloadStates.t = payloadStates.t + mainSys.configParams.jettisonListener.t_trigger;