clear; clc; close all

uc = DRSS.util.unitConv;
%%

fig = figure;
hold on;

windSpeeds = 6.6:0.2:11;
drifts = [];

for windSpeed=windSpeeds
  [~, states] = VADL.sims.solveComp(struct(...
    'disableJettison', true, ...
    'noMotor', false, ...
    'motorLossFactor', 0.965, ...
    'noBallast', false, ...
    'launchAngle', 5, ...
    'launchSiteElevation', 800, ...
    'launchSiteTemp', 60, ...
    'launchSitePressurePa', 91550, ...
    'motorOverride', 'L1720', ...
    'launchRailEffectiveTravel', 12, ... % ft
    'windSpeed', windSpeed, ...
    'driftCalcWindSpeed', 5));

  drifts(end+1) = states.x(end) .* uc.m_to_ft;
end

plot(windSpeeds, drifts, 'DisplayName', 'Jettison Case')
hold on;
xlabel("Wind Speed (mph)");
ylabel("Drift from pad");
legend