function sys = buildFullRocketSystem(sys)

sys = sys ...
  .subjectTo(sys.configParams.gravityDynamics) ...
  ... Ascent-specific:
  .subjectTo(sys.configParams.launchRail) ...
  .subjectTo(sys.configParams.motorDynamics) ...
  .subjectTo(sys.configParams.rocketDynamics) ...
  ... Descent-specific:
  .subjectTo(sys.configParams.drogue) ...
  .subjectTo(sys.configParams.main) ...
  .subjectTo(sys.configParams.rocketDrogueDescentDrag) ...
  .subjectTo(sys.configParams.rocketMainDescentDrag) ...
  ... Special dynamics:
  .subjectTo(sys.configParams.constantThetadDynamics) ...
  .subjectTo(sys.configParams.jettisonEvent) ...
  ... Triggers:
  .subjectTo(sys.configParams.apogeeListener) ...
  .subjectTo(sys.configParams.disableAscentDynamics) ...
  .subjectTo(sys.configParams.mainDeploymentListener) ...
  .subjectTo(sys.configParams.disableDrogueDynamics) ...
  .subjectTo(sys.configParams.jettisonListener);

% Calculate geometry based on system length with massing now available:
sys.configParams.rocketDynamics.recalcTransientParameters(sys);