uc = DRSS.util.unitConv;

files = dir('./+VADL/Motor Data/L*.csv');

for k = 1:length(files)
  filename = files(k).name;
  motortype = filename(1:end-4);

  % disp(['## Processing motor type: ', motortype]);

  sys = VADL.config.getMainSys(struct('motorOverride', motortype));
  %% Solve
  solver = DRSS.solver.MatlabODESolver(sys) ...
    .setCaptureResultantParameters(false) ...
    .configureODE('RelTol', 1e-3, 'AbsTol', 1e-4) ...
    .setPrintPerformanceSummary(false) ...
    .overrideODEFunc(@ode45);

  [resultantStates, resultantParameters] = solver.solve();
  fprintf('%s, %.2f ft, %.2f s, %.2f lb-ft\n', ...
    motortype, ...
    max(resultantStates.y * uc.m_to_ft), ...
    resultantStates.t(end) - sys.configParams.apogeeListener.t_trigger, ...
    resultantStates.yd(end)^2 * 0.5 * sys.configParams.recoveryBay.m * uc.J_to_ftlbf);
end