function sys = descentDrag(sys)

rocketDynamics = sys.configParams.rocketDynamics;
rocketDynamics.recalcTransientParameters(sys);

CDr_drogue = (1.42 * 1.41 * rocketDynamics.aerodynamicProfile.A_fin + 0.56 * (rocketDynamics.A_side)) / rocketDynamics.A;

sys.configParams.rocketMainDescentDrag = DRSS.core.dynamics.SimpleDrag() ...
  .setArea(rocketDynamics.A) ...
  .setCD(CDr_drogue) ...
  .setArea_side(rocketDynamics.A_side) ...
  .setCD_side(1) ...
  .setEnabledOnInit(false);