function sys = massGroups(sys)

uc = DRSS.util.unitConv;

rocketCylindricalInertialGeometry = struct( ...
  'Ri', sys.configParams.rocket_diameter / 2 - 0.085 * uc.in_to_m, ...
  'Ro', sys.configParams.rocket_diameter / 2 ...
);


sys.configParams.rocketTubeMeasured = DRSS.core.obj.MassGroup("Tube") ...
  .appendChild(DRSS.core.obj.Mass("Tube") ...
    .setM((12.1) * uc.lbm_to_kg) ...
    .setLen(60.6 * uc.in_to_m) ... length minus motor
    .setCGX(28.172 * uc.in_to_m)); % no motor

sys = sys ...
  .appendChild(sys.configParams.rocketTubeMeasured) ...
  .setInertialGeometryRecursive(rocketCylindricalInertialGeometry);