function sys = parachutes(sys)

uc = DRSS.util.unitConv;

sys.configParams.main = DRSS.core.dynamics.Parachute() ...
  .setDiameter(48 * uc.in_to_m) ...
  .setCD(2.2) ...
  .setN(9) ... (toroidal = 9, elliptical = 8)
  .setOpeningModel(DRSS.core.dynamics.ParachuteOpeningModel.EXPONENTIAL) ...
  .setEnabledOnInit(false);
